# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI proccess admin web newus

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20]
    env:
      baseUrl: https://api-services.newus.id/api
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Git pull
      run: |
          cd /home/newus-admin/htdocs/admin.newus.id
          git pull
    - run: yarn install
    - name : change repo
      run : cd /home/newus-admin/htdocs/admin.newus.id/actions-runner/_work/admin-webnewus/admin-webnewus
    - run : pm2 restart bin/www
      
    
